spring:
  cloud:
    gateway:
      routes:
        - id: jsonplaceholder
          uri: https://jsonplaceholder.typicode.com
          predicates:
            - Path=/jsonplaceholder/**
          filters:
            - RewritePath=/jsonplaceholder/(?<segment>.*),/$\{segment}
            - ResponseJsonBodyExamples

filters:
  response-body-views:
    path-to-view-mapping: # order == priority
      - path-pattern: "/jsonplaceholder/todos"
        view-class: de.sluit.gateway.views.jsonplaceholder.TodoItemView
      - path-pattern: "/jsonplaceholder/todos/\\d+"
        view-class: de.sluit.gateway.views.jsonplaceholder.TodoItemView
  response-body-examples:
    path-to-example-mapping: # order == priority
      - path-pattern: "/jsonplaceholder/todos"
        example-file-path: "/examples/todo-items.json"
      - path-pattern: "/jsonplaceholder/todos/\\d+"
        example-file-path: "/examples/todo-item.json"
      - path-pattern: "/jsonplaceholder/users"
        example-file-path: "/examples/users.json"
      - path-pattern: "/jsonplaceholder/users/\\d+"
        example-file-path: "/examples/user.json"
